# Generated by Django 5.2.8 on 2025-11-17 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0008_add_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('local', models.CharField(max_length=200)),
                ('data_evento', models.DateField()),
                ('data_limite_inscricao', models.DateField()),
                ('regulamento', models.FileField(blank=True, null=True, upload_to='regulamentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('parametros_baseado_em', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_baseados', to='eventos.evento', verbose_name='Parâmetros baseados em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='EventoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade_min', models.IntegerField(default=0, verbose_name='Idade Mínima')),
                ('idade_max', models.IntegerField(default=99, verbose_name='Idade Máxima')),
                ('usar_pesagem', models.BooleanField(default=True, verbose_name='Usar Pesagem')),
                ('usar_chaves_automaticas', models.BooleanField(default=True, verbose_name='Gerar Chaves Automaticamente')),
                ('permitir_festival', models.BooleanField(default=False, verbose_name='Permitir Festival (3-6 anos)')),
                ('pontuacao_primeiro', models.IntegerField(default=10, verbose_name='Pontuação 1º Lugar')),
                ('pontuacao_segundo', models.IntegerField(default=7, verbose_name='Pontuação 2º Lugar')),
                ('pontuacao_terceiro', models.IntegerField(default=5, verbose_name='Pontuação 3º Lugar')),
                ('penalidade_remanejamento', models.IntegerField(default=1, verbose_name='Penalidade por Remanejamento (pontos)')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Parâmetro do Evento',
                'verbose_name_plural': 'Parâmetros dos Eventos',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('peso_oficial', models.FloatField(blank=True, null=True, verbose_name='Peso Oficial (kg)')),
                ('categoria_ajustada', models.CharField(blank=True, max_length=100, verbose_name='Categoria Ajustada')),
                ('status', models.CharField(choices=[('Inscrito', 'Inscrito'), ('Pesado', 'Pesado'), ('Desclassificado', 'Desclassificado'), ('Remanejado', 'Remanejado')], default='Inscrito', max_length=30)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='atletas.academia')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='atletas.atleta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento')),
                ('inscrito_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
                'unique_together': {('evento', 'atleta')},
            },
        ),
    ]
