# Generated by Django 5.2.8 on 2025-11-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='status_pesagem',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'OK'), ('REMANEJADO', 'Remanejado'), ('DESC', 'Desclassificado')], default='PENDENTE', max_length=20, verbose_name='Status da Pesagem'),
        ),
    ]
