# Generated by Django 5.2.8 on 2025-11-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_inscricao_status_pesagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pesagem_encerrada',
            field=models.BooleanField(default=False, verbose_name='Pesagem Encerrada'),
        ),
    ]
