# Generated by Django 5.2.8 on 2025-11-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_pesagem_encerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor_federado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor Inscrição Federado (R$)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_nao_federado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor Inscrição Não Federado (R$)'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='valor_inscricao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Inscrição (R$)'),
        ),
    ]
