# Generated by Django 5.2.8 on 2025-11-17 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0010_atleta_federado_atleta_zempo'),
        ('eventos', '0004_evento_valor_federado_evento_valor_nao_federado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('peso_oficial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Oficial (kg)')),
                ('categoria_ajustada', models.CharField(blank=True, max_length=100, verbose_name='Categoria Ajustada (nome)')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('REMANEJADO', 'Remanejado'), ('DESCLASSIFICADO', 'Desclassificado'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=30, verbose_name='Status no Evento')),
                ('status_pesagem', models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'OK'), ('REMANEJADO', 'Remanejado'), ('DESC', 'Desclassificado')], default='PENDENTE', max_length=20, verbose_name='Status da Pesagem')),
                ('remanejado', models.BooleanField(default=False, verbose_name='Foi Remanejado?')),
                ('desclassificado', models.BooleanField(default=False, verbose_name='Foi Desclassificado?')),
                ('valor_inscricao', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Inscrição (R$)')),
                ('pontos_evento', models.IntegerField(default=0, verbose_name='Pontos no Evento')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_atletas', to='atletas.academia')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_atletas', to='atletas.atleta')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_atletas', to='atletas.categoria', verbose_name='Categoria no Evento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_atletas', to='eventos.evento')),
                ('inscrito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_atletas_inscritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atleta no Evento',
                'verbose_name_plural': 'Atletas nos Eventos',
                'ordering': ['-data_inscricao'],
                'unique_together': {('evento', 'atleta')},
            },
        ),
        # NÃO deletar Inscricao ainda - será feito após migração de dados
    ]
