# Generated by Django 5.2.8 on 2025-11-17 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0011_chave_evento'),
        ('eventos', '0006_migrate_inscricao_to_eventoatleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('INSCRICOES_ABERTAS', 'Inscrições Abertas'), ('PESAGEM', 'Em Pesagem'), ('CHAVES', 'Chaves Geradas'), ('EM_ANDAMENTO', 'Em Andamento'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=20, verbose_name='Status do Evento'),
        ),
        migrations.AddField(
            model_name='eventoatleta',
            name='categoria_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_atletas_final', to='atletas.categoria', verbose_name='Categoria Final'),
        ),
        migrations.AddField(
            model_name='eventoatleta',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
    ]
