# Generated by Django 5.2.8 on 2025-11-17 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0011_chave_evento'),
        ('eventos', '0007_evento_cidade_evento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoatleta',
            name='categoria_inicial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_iniciais', to='atletas.categoria', verbose_name='Categoria Inicial'),
        ),
        migrations.AddField(
            model_name='eventoatleta',
            name='classe',
            field=models.CharField(blank=True, max_length=20, verbose_name='Classe no Evento'),
        ),
        migrations.AddField(
            model_name='eventoatleta',
            name='peso_previsto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Previsto (kg)'),
        ),
        migrations.AddField(
            model_name='eventoatleta',
            name='pontos',
            field=models.IntegerField(default=0, verbose_name='Pontos no Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_limite_inscricao',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Inscrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('INSCRICOES', 'Inscrições Abertas'), ('PESAGEM', 'Pesagem'), ('ANDAMENTO', 'Em andamento'), ('ENCERRADO', 'Encerrado')], default='ENCERRADO', max_length=20, verbose_name='Status do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='eventoatleta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_atletas', to='atletas.categoria', verbose_name='Categoria no Evento (compatibilidade)'),
        ),
        migrations.AlterField(
            model_name='eventoatleta',
            name='categoria_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_finais', to='atletas.categoria', verbose_name='Categoria Final'),
        ),
        migrations.AlterField(
            model_name='eventoatleta',
            name='desclassificado',
            field=models.BooleanField(default=False, verbose_name='Foi Desclassificado? (compatibilidade)'),
        ),
        migrations.AlterField(
            model_name='eventoatleta',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='eventoatleta',
            name='pontos_evento',
            field=models.IntegerField(default=0, verbose_name='Pontos no Evento (alias)'),
        ),
        migrations.AlterField(
            model_name='eventoatleta',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('ELIMINADO_PESO', 'Eliminado por peso'), ('ELIMINADO_IND', 'Eliminado por indisciplina')], default='OK', max_length=30, verbose_name='Status no Evento'),
        ),
        migrations.AlterField(
            model_name='eventoatleta',
            name='status_pesagem',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('OK', 'OK'), ('REMANEJADO', 'Remanejado'), ('DESC', 'Desclassificado')], default='PENDENTE', max_length=20, verbose_name='Status da Pesagem (compatibilidade)'),
        ),
    ]
