# Generated by Django 5.2.8 on 2025-11-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_eventoatleta_categoria_inicial_eventoatleta_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aceita_nao_federado',
            field=models.BooleanField(default=True, verbose_name='Aceita Não Federados?'),
        ),
        migrations.AddField(
            model_name='evento',
            name='aceita_remanejamento',
            field=models.BooleanField(default=True, verbose_name='Aceita Remanejamento?'),
        ),
        migrations.AddField(
            model_name='eventoatleta',
            name='federado',
            field=models.BooleanField(default=False, verbose_name='É Federado?'),
        ),
        migrations.AddField(
            model_name='eventoatleta',
            name='zempo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número ZEMPO'),
        ),
    ]
