# Generated by Django 5.2.8 on 2025-11-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_ajustar_campos_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='parametros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_limite_inscricao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('INSCRICOES', 'Inscrições Abertas'), ('PESAGEM', 'Pesagem'), ('ANDAMENTO', 'Em andamento'), ('ENCERRADO', 'Encerrado')], default='RASCUNHO', max_length=20, verbose_name='Status do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor_federado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor Inscrição Federado (R$)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='valor_nao_federado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Valor Inscrição Não Federado (R$)'),
        ),
    ]
