# Generated by Django 5.2.8 on 2025-12-14 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('category_code', models.CharField(max_length=50)),
                ('format', models.CharField(choices=[('SINGLE_ELIMINATION', 'Single Elimination'), ('ROUND_ROBIN', 'Round Robin')], max_length=30)),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('event_id', 'category_code')},
            },
        ),
        migrations.CreateModel(
            name='BracketParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_id', models.UUIDField()),
                ('athlete_id', models.UUIDField()),
                ('organization_id', models.UUIDField()),
                ('seed', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='brackets.bracket')),
            ],
            options={
                'unique_together': {('bracket', 'athlete_id')},
            },
        ),
    ]
