# Generated by Django 5.2.8 on 2025-12-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bracket',
            name='belt_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='class_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='format',
            field=models.CharField(choices=[('SINGLE_ELIMINATION', 'Single Elimination'), ('ROUND_ROBIN', 'Round Robin'), ('BEST_OF_3', 'Best of 3'), ('ELIMINATION_WITH_REPECHAGE', 'Elimination with Repechage')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together={('event_id', 'category_code', 'class_code', 'sex', 'belt_group')},
        ),
    ]
