# Generated by Django 5.2.8 on 2025-12-14 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('class_code', models.CharField(max_length=50)),
                ('category_code', models.CharField(max_length=50)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('sex', 'class_code', 'category_code')},
            },
        ),
    ]
