# Generated by Django 5.2.8 on 2025-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('OPERATIONS', 'Operations'), ('ACADEMY_ADMIN', 'Academy Admin'), ('ACADEMY_STAFF', 'Academy Staff'), ('WEIGHING_OFFICIAL', 'Weighing Official'), ('TABLE_OFFICIAL', 'Table Official')], max_length=30),
        ),
    ]
