# Generated by Django 5.2.8 on 2025-11-16 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('pontos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Academia',
                'verbose_name_plural': 'Academias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('categoria_nome', models.CharField(max_length=100)),
                ('limite_min', models.FloatField()),
                ('limite_max', models.FloatField()),
                ('label', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['classe', 'sexo', 'limite_min'],
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ano_nasc', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('faixa', models.CharField(max_length=50)),
                ('classe', models.CharField(blank=True, max_length=20)),
                ('categoria_nome', models.CharField(blank=True, max_length=100)),
                ('categoria_limite', models.CharField(blank=True, max_length=50)),
                ('peso_previsto', models.FloatField(blank=True, null=True)),
                ('peso_oficial', models.FloatField(blank=True, null=True)),
                ('categoria_ajustada', models.CharField(blank=True, max_length=100)),
                ('motivo_ajuste', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Eliminado Peso', 'Eliminado por Peso'), ('Eliminado Indisciplina', 'Eliminado por Indisciplina')], default='OK', max_length=30)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='atletas.academia')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('categoria', models.CharField(max_length=100)),
                ('estrutura', models.JSONField(default=dict)),
                ('atletas', models.ManyToManyField(related_name='chaves', to='atletas.atleta')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'ordering': ['classe', 'sexo', 'categoria'],
            },
        ),
        migrations.CreateModel(
            name='Luta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('proxima_luta', models.IntegerField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('atleta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lutas_como_a', to='atletas.atleta')),
                ('atleta_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lutas_como_b', to='atletas.atleta')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutas', to='atletas.chave')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lutas_vencidas', to='atletas.atleta')),
            ],
            options={
                'verbose_name': 'Luta',
                'verbose_name_plural': 'Lutas',
                'ordering': ['chave', 'round', 'id'],
            },
        ),
    ]
