# Generated by Django 5.2.8 on 2025-11-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='remanejado',
            field=models.BooleanField(default=False),
        ),
    ]
