# Generated by Django 5.2.8 on 2025-11-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_atleta_remanejado'),
    ]

    operations = [
        migrations.AddField(
            model_name='luta',
            name='ippon_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luta',
            name='pontos_perdedor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luta',
            name='pontos_vencedor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luta',
            name='tipo_vitoria',
            field=models.CharField(blank=True, choices=[('IPPON', 'Ippon'), ('WAZARI', 'Wazari'), ('WAZARI_WAZARI', 'Wazari-Wazari'), ('YUKO', 'Yuko')], max_length=20),
        ),
        migrations.AddField(
            model_name='luta',
            name='wazari_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='luta',
            name='yuko_count',
            field=models.IntegerField(default=0),
        ),
    ]
