# Generated by Django 5.2.8 on 2025-11-16 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_luta_ippon_count_luta_pontos_perdedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('acao', models.CharField(max_length=200)),
                ('usuario_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log Administrativo',
                'verbose_name_plural': 'Logs Administrativos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
