# Generated by Django 5.2.8 on 2025-11-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_adminlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Campeonato Padrão', max_length=200)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-data_inicio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AcademiaPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouro', models.IntegerField(default=0)),
                ('prata', models.IntegerField(default=0)),
                ('bronze', models.IntegerField(default=0)),
                ('quarto', models.IntegerField(default=0)),
                ('quinto', models.IntegerField(default=0)),
                ('festival', models.IntegerField(default=0)),
                ('remanejamento', models.IntegerField(default=0)),
                ('pontos_totais', models.IntegerField(default=0)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='atletas.academia')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='atletas.campeonato')),
            ],
            options={
                'verbose_name': 'Pontuação de Academia',
                'verbose_name_plural': 'Pontuações de Academias',
                'ordering': ['-pontos_totais', 'academia__nome'],
                'unique_together': {('campeonato', 'academia')},
            },
        ),
    ]
