# Generated by Django 5.2.8 on 2025-11-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_campeonato_academiapontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone de contato da academia', max_length=20),
        ),
        migrations.AddField(
            model_name='atleta',
            name='federado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='regulamento',
            field=models.TextField(blank=True, help_text='Regulamento do campeonato'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='valor_inscricao_federado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da inscrição para atletas federados', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='valor_inscricao_nao_federado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da inscrição para atletas não federados', max_digits=10, null=True),
        ),
    ]
