# Generated by Django 5.2.8 on 2025-11-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_campeonato_academiapontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_academias/'),
        ),
        migrations.AddField(
            model_name='academia',
            name='sigla',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='academia',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
