# Generated by Django 5.2.8 on 2025-11-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0006_add_academia_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='senha_externa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='local',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='prazo_inscricao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
