# Generated by Django 5.2.8 on 2025-11-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0006_academia_telefone_atleta_federado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeonato',
            name='data_fim',
        ),
        migrations.AddField(
            model_name='campeonato',
            name='data_competicao',
            field=models.DateField(blank=True, help_text='Data da competição', null=True),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='data_limite_inscricao',
            field=models.DateField(blank=True, help_text='Data limite para inscrições', null=True),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Data de início das inscrições', null=True),
        ),
    ]
