# Generated by Django 5.2.8 on 2025-11-17 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0007_add_portal_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('academia', 'Academia'), ('operacional', 'Operacional/Gestão'), ('admin', 'Administrador')], default='operacional', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('pode_inscricao', models.BooleanField(default=True)),
                ('pode_pesagem', models.BooleanField(default=True)),
                ('pode_chave', models.BooleanField(default=True)),
                ('pode_dashboard', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='atletas.academia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['user__username'],
            },
        ),
    ]
