# Generated by Django 5.2.8 on 2025-11-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0007_remove_campeonato_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='numero_zempo',
            field=models.CharField(blank=True, help_text='Número Zempo (obrigatório para atletas federados)', max_length=50, null=True),
        ),
    ]
