# Generated by Django 5.2.8 on 2025-12-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0007_pesagem_flow_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='bloqueado_chave',
            field=models.BooleanField(default=False, verbose_name='Bloqueado para chaveamento'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academias', to='atletas.organizador', verbose_name='Organização'),
        ),
        migrations.AlterField(
            model_name='campeonato',
            name='ativo',
            field=models.BooleanField(default=False, help_text='Apenas um campeonato pode estar ativo por vez'),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único usado nas URLs.', max_length=80, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
