# Generated by Django 5.2.8 on 2025-11-24 00:59

import atletas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0008_atleta_numero_zempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='categoria_ajustada',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='categoria_limite',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='categoria_nome',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='faixa',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='motivo_ajuste',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='peso_oficial',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='peso_previsto',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='remanejado',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='status',
        ),
        migrations.AddField(
            model_name='atleta',
            name='classe_inicial',
            field=models.CharField(blank=True, help_text='Classe base do atleta (calculada automaticamente)', max_length=20, verbose_name='Classe Inicial'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='documento_oficial',
            field=models.FileField(blank=True, help_text='Upload de documento de identidade (JPG, PNG ou PDF)', null=True, upload_to=atletas.models.documento_upload_path, verbose_name='Documento Oficial'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='status_ativo',
            field=models.BooleanField(default=True, help_text='Atleta ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='academia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='atletas.academia', verbose_name='Academia'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='ano_nasc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Nascimento'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='federado',
            field=models.BooleanField(default=False, verbose_name='Federado'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='numero_zempo',
            field=models.CharField(blank=True, help_text='Número Zempo (obrigatório para atletas federados)', max_length=50, null=True, verbose_name='Número Zempo'),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_escolhida', models.CharField(max_length=20, verbose_name='Classe Escolhida')),
                ('categoria_escolhida', models.CharField(blank=True, max_length=100, verbose_name='Categoria Escolhida')),
                ('peso', models.FloatField(blank=True, null=True, verbose_name='Peso Oficial (kg)')),
                ('categoria_ajustada', models.CharField(blank=True, max_length=100, verbose_name='Categoria Ajustada')),
                ('motivo_ajuste', models.TextField(blank=True, verbose_name='Motivo do Ajuste')),
                ('remanejado', models.BooleanField(default=False, verbose_name='Remanejado')),
                ('status_inscricao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='Status da Inscrição')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('data_pesagem', models.DateTimeField(blank=True, null=True, verbose_name='Data da Pesagem')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='atletas.atleta', verbose_name='Atleta')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='atletas.campeonato', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
                'unique_together': {('atleta', 'campeonato')},
            },
        ),
    ]
