# Generated by Django 5.2.8 on 2025-11-17 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0008_add_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='academia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='atletas.academia'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='atleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='atletas.atleta'),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='tipo',
            field=models.CharField(choices=[('REMANEJAMENTO', 'Remanejamento'), ('DESCLASSIFICACAO', 'Desclassificação'), ('PESAGEM', 'Pesagem'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20),
        ),
    ]
