# Generated by Django 5.2.8 on 2025-11-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0009_adminlog_academia_adminlog_atleta_adminlog_detalhes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='federado',
            field=models.BooleanField(default=False, verbose_name='É Federado?'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='zempo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número ZEMPO'),
        ),
    ]
