# Generated by Django 5.2.8 on 2025-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0009_remove_atleta_categoria_ajustada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='ativo_login',
            field=models.BooleanField(default=True, help_text='Permite login da academia'),
        ),
        migrations.AddField(
            model_name='academia',
            name='email_login',
            field=models.EmailField(blank=True, help_text='E-mail para login da academia', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academia',
            name='senha_login',
            field=models.CharField(blank=True, help_text='Senha para login (será criptografada)', max_length=128),
        ),
    ]
