# Generated by Django 5.2.8 on 2025-11-17 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0010_atleta_federado_atleta_zempo'),
        ('eventos', '0006_migrate_inscricao_to_eventoatleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='eventos.evento', verbose_name='Evento'),
        ),
    ]
