# Generated by Django 5.2.8 on 2025-11-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0010_add_academia_login_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('atleta', 'campeonato', 'classe_escolhida', 'categoria_escolhida')},
        ),
    ]
