# Generated by Django 5.2.8 on 2025-11-24 03:37

import atletas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0011_allow_multiple_inscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil da academia (JPG, PNG)', null=True, upload_to=atletas.models.foto_perfil_academia_upload_path, verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil do atleta (JPG, PNG)', null=True, upload_to=atletas.models.foto_perfil_atleta_upload_path, verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='luta',
            name='tipo_vitoria',
            field=models.CharField(blank=True, choices=[('IPPON', 'Ippon'), ('WAZARI', 'Wazari'), ('YUKO', 'Yuko')], max_length=20),
        ),
    ]
