# Generated by Django 5.2.8 on 2025-11-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0012_add_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='faixa',
            field=models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('P.CINZA', 'P. Cinza'), ('CINZA', 'Cinza'), ('P.AZUL', 'P. Azul'), ('AZUL', 'Azul'), ('P.AMARELA', 'P. Amarela'), ('AMARELA', 'Amarela'), ('P.LARANJA', 'P. Laranja'), ('LARANJA', 'Laranja'), ('VERDE', 'Verde'), ('ROXA', 'Roxa'), ('MARRON', 'Marrom'), ('PRETA', 'Preta')], help_text='Graduação do atleta', max_length=20, null=True, verbose_name='Faixa'),
        ),
    ]
