# Generated by Django 5.2.8 on 2025-11-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0013_merge_0010_0012'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='luta',
            new_name='atletas_lut_evento__302d7e_idx',
            old_name='atletas_lut_evento_c_idx',
        ),
        migrations.RenameIndex(
            model_name='luta',
            new_name='atletas_lut_evento__12c271_idx',
            old_name='atletas_lut_evento_r_idx',
        ),
        migrations.AddField(
            model_name='academia',
            name='senha_acesso',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha de Acesso (hash)'),
        ),
        migrations.AddField(
            model_name='academia',
            name='usuario_acesso',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Usuário de Acesso'),
        ),
    ]
