# Generated by Django 5.2.8 on 2025-11-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0013_add_faixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arbitro', 'Árbitro'), ('mesario', 'Mesário'), ('coordenador', 'Coordenador'), ('oficial_pesagem', 'Oficial de Pesagem'), ('oficial_mesa', 'Oficial de Mesa'), ('ambulancia', 'Ambulância'), ('patrocinador', 'Patrocinador'), ('insumo', 'Insumo')], max_length=50, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cadastro Operacional',
                'verbose_name_plural': 'Cadastros Operacionais',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='academia',
            name='email_login',
        ),
        migrations.AddField(
            model_name='academia',
            name='bonus_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo de bônus por atleta confirmado', max_digits=10, null=True, verbose_name='Bônus Fixo por Atleta'),
        ),
        migrations.AddField(
            model_name='academia',
            name='bonus_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de bônus sobre inscrições confirmadas', max_digits=5, null=True, verbose_name='Bônus Percentual (%)'),
        ),
        migrations.AddField(
            model_name='academia',
            name='login',
            field=models.CharField(blank=True, help_text='Login da academia (email ou telefone)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academia',
            name='responsavel',
            field=models.CharField(blank=True, help_text='Nome do responsável pela academia', max_length=200, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status_inscricao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20, verbose_name='Status da Inscrição'),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('arbitros', 'Árbitros'), ('mesarios', 'Mesários'), ('coordenadores', 'Coordenadores'), ('oficiais_pesagem', 'Oficiais de Pesagem'), ('oficiais_mesa', 'Oficiais de Mesa'), ('insumos', 'Insumos'), ('ambulancia', 'Ambulância'), ('patrocinios', 'Patrocínios (entrada)'), ('estrutura', 'Estrutura'), ('limpeza', 'Limpeza'), ('outras', 'Outras')], max_length=50, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='atletas.campeonato', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
