# Generated by Django 5.2.8 on 2025-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0014_adicionar_login_academia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='tipo_chave',
            field=models.CharField(blank=True, choices=[('MELHOR_DE_3', 'Melhor de 3 (2 atletas)'), ('CASADA_3', 'Lutas casadas para 3 atletas (A x B → Perdedor x C → Final)'), ('SIMPLES_3', 'Eliminatória Simples com 3 atletas (Stand-by)'), ('RODIZIO', 'Rodízio (3 a 5 atletas)'), ('ELIMINATORIA_SIMPLES', 'Eliminatória Simples'), ('ELIMINATORIA_REPESCAGEM', 'Eliminatória com Repescagem (modelo CBJ)'), ('OLIMPICA', 'Chave Olímpica (IJF)'), ('LIGA', 'Chave Liga (rodízio + semifinais)'), ('GRUPOS', 'Chave em Grupos (pools)')], max_length=30, null=True, verbose_name='Tipo de Chave'),
        ),
    ]
