# Generated by Django 5.2.8 on 2025-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0014_add_modulos_academia_administracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contato Responsável'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='contato_whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp do Contato'),
        ),
    ]
