# Generated by Django 5.2.8 on 2025-11-25 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0015_add_despesa_contato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_resetar_campeonato', models.BooleanField(default=False, help_text='Permissão para resetar campeonato (apenas usuário principal)', verbose_name='Pode Resetar Campeonato')),
                ('pode_criar_usuarios', models.BooleanField(default=False, help_text='Permissão para criar novos usuários operacionais (apenas usuário principal)', verbose_name='Pode Criar Usuários')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Data de expiração do acesso (null = vitalício)', null=True, verbose_name='Data de Expiração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_operacional', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário Operacional',
                'verbose_name_plural': 'Usuários Operacionais',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
