# Generated by Django 5.2.8 on 2025-11-25 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0016_usuariooperacional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademiaCampeonatoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha (criptografada)')),
                ('senha_plana', models.CharField(help_text='Senha em texto plano (apenas para exibição inicial)', max_length=20, verbose_name='Senha Plana')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('enviado_whatsapp', models.BooleanField(default=False, verbose_name='Enviado por WhatsApp')),
                ('data_envio_whatsapp', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio WhatsApp')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senhas_campeonatos', to='atletas.academia', verbose_name='Academia')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senhas_academias', to='atletas.campeonato', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Senha de Academia por Campeonato',
                'verbose_name_plural': 'Senhas de Academias por Campeonato',
                'ordering': ['-data_criacao'],
                'unique_together': {('academia', 'campeonato')},
            },
        ),
    ]
