# Generated by Django 5.2.8 on 2025-11-25 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0017_academiacampeonatosenha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'ordering': ['-campeonato__data_competicao', 'classe', 'sexo', 'categoria'], 'verbose_name': 'Chave', 'verbose_name_plural': 'Chaves'},
        ),
        migrations.AddField(
            model_name='chave',
            name='campeonato',
            field=models.ForeignKey(blank=True, help_text='Campeonato ao qual esta chave pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='atletas.campeonato', verbose_name='Campeonato'),
        ),
    ]
