# Generated by Django 5.2.8 on 2025-11-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0018_add_campeonato_to_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço da academia (opcional)', max_length=300, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='academiacampeonatosenha',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, help_text='Data de expiração do acesso (5 dias após término do campeonato)', null=True, verbose_name='Data de Expiração'),
        ),
        migrations.AddField(
            model_name='academiacampeonatosenha',
            name='login',
            field=models.CharField(blank=True, help_text='Login gerado automaticamente (ex: ACADEMIA_045)', max_length=50, null=True, verbose_name='Login Temporário'),
        ),
        migrations.AlterField(
            model_name='academia',
            name='login',
            field=models.CharField(blank=True, help_text='[DEPRECADO] Login da academia - não usar mais', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academia',
            name='senha_login',
            field=models.CharField(blank=True, help_text='[DEPRECADO] Senha para login - não usar mais', max_length=128),
        ),
    ]
