# Generated by Django 5.2.8 on 2025-11-26 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0019_adicionar_campos_credenciais_temporarias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('PIX', 'PIX'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='campeonato',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Chave PIX para pagamento (CPF, CNPJ, Email, Telefone ou Chave Aleatória)', max_length=200, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='titular_pix',
            field=models.CharField(blank=True, help_text='Nome do titular da conta PIX', max_length=200, verbose_name='Titular da Chave PIX'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='formas_pagamento',
            field=models.ManyToManyField(blank=True, help_text='Selecione as formas de pagamento aceitas para este evento', to='atletas.formapagamento', verbose_name='Formas de Pagamento Aceitas'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('comprovante', models.FileField(help_text='Comprovante de pagamento (JPG, PNG ou PDF)', upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Pagamento'), ('AGUARDANDO', 'Aguardando Validação'), ('VALIDADO', 'Validado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Motivo da rejeição do pagamento (preenchido pelo operador)', verbose_name='Motivo da Rejeição')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='atletas.academia', verbose_name='Academia')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='atletas.campeonato', verbose_name='Campeonato')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_envio'],
                'unique_together': {('academia', 'campeonato')},
            },
        ),
    ]
