# Generated by Django 5.2.8 on 2025-11-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0020_formapagamento_campeonato_chave_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Chave PIX para pagamento (obrigatório para equipe técnica)', max_length=200, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='funcao_equipe_tecnica',
            field=models.CharField(blank=True, help_text='Função padrão na equipe técnica (ex: Árbitro, Mesário, Coordenador)', max_length=100, null=True, verbose_name='Função/Cargo na Equipe Técnica'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='pode_ser_equipe_tecnica',
            field=models.BooleanField(default=False, help_text='Permite que esta pessoa seja selecionada para compor a equipe técnica em eventos', verbose_name='Pode Fazer Parte da Equipe Técnica'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(help_text='Comprovante de pagamento (JPG, PNG, PDF ou HEIC)', upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante'),
        ),
        migrations.CreateModel(
            name='EquipeTecnicaCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('arbitro', 'Árbitro'), ('mesario', 'Mesário'), ('coordenador', 'Coordenador'), ('oficial_pesagem', 'Oficial de Pesagem'), ('oficial_mesa', 'Oficial de Mesa'), ('outro', 'Outro')], help_text='Função específica neste campeonato', max_length=50, verbose_name='Função no Evento')),
                ('funcao_customizada', models.CharField(blank=True, help_text="Se 'Outro', especifique a função", max_length=100, null=True, verbose_name='Função Customizada')),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre a participação desta pessoa na equipe técnica', verbose_name='Observação')),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Vinculação')),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, a pessoa não faz parte da equipe técnica deste evento', verbose_name='Ativo')),
                ('atleta', models.ForeignKey(help_text='Pessoa cadastrada no sistema', on_delete=django.db.models.deletion.CASCADE, related_name='equipe_tecnica_vinculos', to='atletas.atleta', verbose_name='Pessoa')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_tecnica', to='atletas.campeonato', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Membro da Equipe Técnica',
                'verbose_name_plural': 'Equipe Técnica',
                'ordering': ['campeonato', 'funcao', 'atleta__nome'],
                'unique_together': {('atleta', 'campeonato', 'funcao')},
            },
        ),
    ]
