# Generated by Django 5.2.8 on 2025-11-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0021_atleta_chave_pix_atleta_funcao_equipe_tecnica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipetecnicacampeonato',
            options={'ordering': ['campeonato', 'funcao'], 'verbose_name': 'Membro da Equipe Técnica', 'verbose_name_plural': 'Equipe Técnica'},
        ),
        migrations.AlterUniqueTogether(
            name='equipetecnicacampeonato',
            unique_together={('atleta', 'campeonato', 'funcao')},
        ),
        migrations.AddField(
            model_name='equipetecnicacampeonato',
            name='chave_pix_externo',
            field=models.CharField(blank=True, help_text='Chave PIX para pagamento', max_length=200, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='equipetecnicacampeonato',
            name='nome_externo',
            field=models.CharField(blank=True, help_text='Nome completo da pessoa (se não for atleta cadastrado)', max_length=200, null=True, verbose_name='Nome (Pessoa Externa)'),
        ),
        migrations.AddField(
            model_name='equipetecnicacampeonato',
            name='telefone_externo',
            field=models.CharField(blank=True, help_text='Telefone de contato', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='equipetecnicacampeonato',
            name='atleta',
            field=models.ForeignKey(blank=True, help_text='Selecione um atleta cadastrado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe_tecnica_vinculos', to='atletas.atleta', verbose_name='Atleta'),
        ),
        migrations.AlterUniqueTogether(
            name='equipetecnicacampeonato',
            unique_together={('atleta', 'campeonato', 'funcao'), ('nome_externo', 'campeonato', 'funcao')},
        ),
    ]
