# Generated by Django 5.2.8 on 2025-11-29 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0022_alter_equipetecnicacampeonato_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Tatames, Aluguéis, Transportes, etc.', max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da categoria', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, não aparecerá nas opções', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Categoria de Insumo',
                'verbose_name_plural': 'Categorias de Insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InsumoEstrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Aluguel de tatames, Transporte de equipamentos, etc.', max_length=200, verbose_name='Nome do Item')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('quantidade', models.IntegerField(default=1, help_text='Quantidade de itens ou unidades', verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Valor por unidade (calculado automaticamente)', max_digits=10, null=True, verbose_name='Valor Unitário')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('fornecedor', models.CharField(blank=True, help_text='Nome do fornecedor ou empresa', max_length=200, verbose_name='Fornecedor')),
                ('contato_nome', models.CharField(blank=True, max_length=200, verbose_name='Contato Responsável')),
                ('contato_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp do Contato')),
                ('observacao', models.TextField(blank=True, help_text='Observações adicionais sobre o insumo', verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_estrutura', to='atletas.campeonato', verbose_name='Campeonato')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='atletas.categoriainsumo', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Insumo/Estrutura',
                'verbose_name_plural': 'Insumos e Estrutura',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
