# Generated by Django 5.2.8 on 2025-11-29 15:29

import django.db.models.deletion
from django.db import migrations, models


def migrar_dados_equipe_tecnica(apps, schema_editor):
    """Migra dados existentes de EquipeTecnicaCampeonato para PessoaEquipeTecnica"""
    EquipeTecnicaCampeonato = apps.get_model('atletas', 'EquipeTecnicaCampeonato')
    PessoaEquipeTecnica = apps.get_model('atletas', 'PessoaEquipeTecnica')
    Atleta = apps.get_model('atletas', 'Atleta')
    
    # Migrar registros existentes
    for vinculo in EquipeTecnicaCampeonato.objects.all():
        if vinculo.atleta_id:
            # É um atleta - criar PessoaEquipeTecnica
            pessoa, created = PessoaEquipeTecnica.objects.get_or_create(
                atleta_id=vinculo.atleta_id,
                defaults={
                    'nome': vinculo.atleta.nome if hasattr(vinculo, 'atleta') else '',
                    'telefone': vinculo.telefone_externo or (vinculo.atleta.telefone if hasattr(vinculo, 'atleta') and hasattr(vinculo.atleta, 'telefone') else ''),
                    'chave_pix': vinculo.chave_pix_externo or (vinculo.atleta.chave_pix if hasattr(vinculo, 'atleta') and hasattr(vinculo.atleta, 'chave_pix') else ''),
                }
            )
        elif vinculo.nome_externo:
            # É pessoa externa - criar PessoaEquipeTecnica
            pessoa, created = PessoaEquipeTecnica.objects.get_or_create(
                nome=vinculo.nome_externo,
                atleta=None,
                defaults={
                    'telefone': vinculo.telefone_externo or '',
                    'chave_pix': vinculo.chave_pix_externo or '',
                }
            )
        else:
            continue
        
        # Atualizar vínculo
        vinculo.pessoa = pessoa
        vinculo.save()


def reverter_migracao(apps, schema_editor):
    """Reverter migração (não implementado completamente)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0023_categoriainsumo_insumoestrutura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipetecnicacampeonato',
            options={'ordering': ['campeonato', 'funcao', 'pessoa__nome'], 'verbose_name': 'Membro da Equipe Técnica no Campeonato', 'verbose_name_plural': 'Equipe Técnica nos Campeonatos'},
        ),
        migrations.AlterField(
            model_name='equipetecnicacampeonato',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações sobre a participação desta pessoa na equipe técnica deste evento', verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='PessoaEquipeTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo da pessoa (obrigatório se não for atleta)', max_length=200, verbose_name='Nome Completo')),
                ('telefone', models.CharField(help_text='Telefone para contato e envio de convites', max_length=20, verbose_name='Telefone/WhatsApp')),
                ('chave_pix', models.CharField(help_text='Chave PIX para pagamentos', max_length=200, verbose_name='Chave PIX')),
                ('observacao', models.TextField(blank=True, help_text='Observações gerais sobre esta pessoa', verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, não aparecerá nas opções', verbose_name='Ativo')),
                ('atleta', models.ForeignKey(blank=True, help_text='Selecione um atleta cadastrado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_equipe_tecnica', to='atletas.atleta', verbose_name='Atleta')),
            ],
            options={
                'verbose_name': 'Pessoa da Equipe Técnica',
                'verbose_name_plural': 'Pessoas da Equipe Técnica',
                'ordering': ['nome'],
                'unique_together': {('atleta',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipetecnicacampeonato',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipetecnicacampeonato',
            name='pessoa',
            field=models.ForeignKey(blank=True, help_text='Pessoa da lista fixa de equipe técnica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_campeonatos', to='atletas.pessoaequipetecnica', verbose_name='Pessoa'),
        ),
        migrations.AlterUniqueTogether(
            name='equipetecnicacampeonato',
            unique_together={('pessoa', 'campeonato', 'funcao')},
        ),
        migrations.RemoveField(
            model_name='equipetecnicacampeonato',
            name='atleta',
        ),
        migrations.RemoveField(
            model_name='equipetecnicacampeonato',
            name='chave_pix_externo',
        ),
        migrations.RemoveField(
            model_name='equipetecnicacampeonato',
            name='nome_externo',
        ),
        migrations.RemoveField(
            model_name='equipetecnicacampeonato',
            name='telefone_externo',
        ),
        migrations.RunPython(migrar_dados_equipe_tecnica, reverter_migracao),
        migrations.AlterField(
            model_name='equipetecnicacampeonato',
            name='pessoa',
            field=models.ForeignKey(help_text='Pessoa da lista fixa de equipe técnica', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_campeonatos', to='atletas.pessoaequipetecnica', verbose_name='Pessoa'),
        ),
    ]
