# Generated by Django 5.2.8 on 2025-11-30 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0024_unificar_equipe_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipetecnicacampeonato',
            name='pessoa',
            field=models.ForeignKey(blank=True, help_text='Pessoa da lista fixa de equipe técnica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_campeonatos', to='atletas.pessoaequipetecnica', verbose_name='Pessoa'),
        ),
        migrations.CreateModel(
            name='AcademiaCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitido', models.BooleanField(default=True, help_text='Se desmarcado, a academia não poderá participar deste campeonato', verbose_name='Permitido no Campeonato')),
                ('data_vinculacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Vinculação')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_campeonatos', to='atletas.academia', verbose_name='Academia')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academias_vinculadas', to='atletas.campeonato', verbose_name='Campeonato')),
            ],
            options={
                'verbose_name': 'Academia no Campeonato',
                'verbose_name_plural': 'Academias nos Campeonatos',
                'ordering': ['academia__nome'],
                'unique_together': {('academia', 'campeonato')},
            },
        ),
    ]
