# Generated by Django 5.2.8 on 2025-11-30 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0025_adicionar_academia_campeonato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesagemHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_registrado', models.FloatField(verbose_name='Peso Registrado (kg)')),
                ('categoria_ajustada', models.CharField(blank=True, max_length=100, verbose_name='Categoria Ajustada')),
                ('motivo_ajuste', models.TextField(blank=True, verbose_name='Motivo do Ajuste')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Pesagem')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesagens_historico', to='atletas.campeonato', verbose_name='Campeonato')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pesagens', to='atletas.inscricao', verbose_name='Inscrição')),
                ('pesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesagens_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Pesado por')),
            ],
            options={
                'verbose_name': 'Histórico de Pesagem',
                'verbose_name_plural': 'Históricos de Pesagem',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['campeonato', '-data_hora'], name='atletas_pes_campeon_3898f1_idx'), models.Index(fields=['inscricao', '-data_hora'], name='atletas_pes_inscric_269db9_idx')],
            },
        ),
    ]
