# Generated by Django 5.2.8 on 2025-11-30 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0026_pesagemhistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('DIVERGENTE', 'Divergente')], default='PENDENTE', max_length=20, verbose_name='Status da Conferência')),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Esperado')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido')),
                ('data_conferencia', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conferência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('quantidade_atletas', models.IntegerField(default=0, verbose_name='Quantidade de Atletas')),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias_pagamento', to='atletas.academia', verbose_name='Academia')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias_pagamento', to='atletas.campeonato', verbose_name='Campeonato')),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Conferido por')),
            ],
            options={
                'verbose_name': 'Conferência de Pagamento',
                'verbose_name_plural': 'Conferências de Pagamento',
                'ordering': ['-data_conferencia'],
                'unique_together': {('academia', 'campeonato')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('INSCRICAO', 'Inscrição'), ('PESAGEM', 'Pesagem'), ('PAGAMENTO', 'Pagamento'), ('CONFERENCIA_PAGAMENTO', 'Conferência de Pagamento'), ('CHAVE', 'Geração de Chave'), ('RESULTADO', 'Registro de Resultado'), ('PONTUACAO', 'Cálculo de Pontuação'), ('ACADEMIA', 'Cadastro/Edição de Academia'), ('ATLETA', 'Cadastro/Edição de Atleta'), ('CAMPEONATO', 'Cadastro/Edição de Campeonato'), ('USUARIO', 'Criação/Edição de Usuário'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Tipo de Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados adicionais em formato JSON', null=True, verbose_name='Dados Extras')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to='atletas.academia', verbose_name='Academia')),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to='atletas.atleta', verbose_name='Atleta')),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to='atletas.campeonato', verbose_name='Campeonato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico do Sistema',
                'verbose_name_plural': 'Históricos do Sistema',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['tipo_acao', 'data_hora'], name='atletas_his_tipo_ac_3bf94c_idx'), models.Index(fields=['campeonato', 'data_hora'], name='atletas_his_campeon_31fe18_idx'), models.Index(fields=['usuario', 'data_hora'], name='atletas_his_usuario_6f6467_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('RELATO_PROFESSOR', 'Relato de Professor'), ('PROBLEMA_PESAGEM', 'Problema em Pesagem'), ('INDISCIPLINA', 'Indisciplina'), ('ACIDENTE', 'Acidente'), ('PROBLEMA_TECNICO', 'Problema Técnico'), ('PROBLEMA_ORGANIZACIONAL', 'Problema Organizacional'), ('RECLAMACAO', 'Reclamação'), ('SUGESTAO', 'Sugestão'), ('OUTRO', 'Outro')], max_length=50, verbose_name='Categoria')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDA', 'Resolvida'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('data_ocorrencia', models.DateTimeField(help_text='Data e hora em que o problema ocorreu', verbose_name='Data da Ocorrência')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('solucao', models.TextField(blank=True, verbose_name='Solução Aplicada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Adicionais')),
                ('anexos', models.JSONField(blank=True, help_text='Lista de URLs de arquivos anexados', null=True, verbose_name='Anexos')),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='atletas.academia', verbose_name='Academia')),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='atletas.atleta', verbose_name='Atleta Envolvido')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='atletas.campeonato', verbose_name='Campeonato')),
                ('inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='atletas.inscricao', verbose_name='Inscrição Relacionada')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('responsavel_resolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Resolução')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_ocorrencia', '-data_registro'],
                'indexes': [models.Index(fields=['campeonato', 'status'], name='atletas_oco_campeon_ee902a_idx'), models.Index(fields=['categoria', 'status'], name='atletas_oco_categor_88ace4_idx'), models.Index(fields=['prioridade', 'status'], name='atletas_oco_priorid_8eae61_idx')],
            },
        ),
    ]
