# Generated by Django 5.2.8 on 2025-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0027_conferenciapagamento_historicosistema_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenciapagamento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('DIVERGENTE', 'Divergente'), ('NAO_ENCONTRADO', 'Não Encontrado')], default='PENDENTE', max_length=20, verbose_name='Status da Conferência'),
        ),
    ]
