# Generated by Django 5.2.8 on 2025-11-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0028_alter_conferenciapagamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciapagamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='conferenciapagamento',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Comprovante de pagamento enviado pela academia (JPG, PNG, PDF ou HEIC)', null=True, upload_to='comprovantes/%Y/%m/', verbose_name='Comprovante'),
        ),
    ]
