# Generated by Django 5.2.8 on 2025-11-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0029_conferenciapagamento_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], default='despesa', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='equipetecnicacampeonato',
            name='despesa_gerada',
            field=models.ForeignKey(blank=True, help_text='Despesa gerada automaticamente a partir do pró-labore', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_tecnica_origem', to='atletas.despesa', verbose_name='Despesa Gerada'),
        ),
        migrations.AddField(
            model_name='equipetecnicacampeonato',
            name='pro_labore',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor do pró-labore/salário para esta função (será contabilizado como despesa)', max_digits=10, verbose_name='Pró-Labore'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento/Recebimento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('pago', 'Pago/Recebido'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
