# Generated by Django 5.2.8 on 2025-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0030_adicionar_pro_labore_equipe_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luta',
            name='tipo_vitoria',
            field=models.CharField(blank=True, choices=[('IPPON', 'Ippon'), ('WAZARI', 'Wazari'), ('WAZARI_WAZARI', 'Wazari-Wazari'), ('YUKO', 'Yuko')], max_length=20),
        ),
    ]
