# Generated by Django 5.2.8 on 2025-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0031_adicionar_wazari_wazari'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='data_limite_inscricao_academia',
            field=models.DateField(blank=True, help_text='Após esta data, academias não poderão mais inscrever ou editar atletas. Apenas a equipe operacional poderá fazer inscrições.', null=True, verbose_name='Data Limite para Inscrições por Academia'),
        ),
    ]
