# Generated by Django 5.2.8 on 2025-11-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0032_campeonato_data_limite_inscricao_academia'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pessoaequipetecnica',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Chave PIX para pagamentos', max_length=200, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='pessoaequipetecnica',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome completo da pessoa (obrigatório se não for atleta)', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='pessoaequipetecnica',
            name='telefone',
            field=models.CharField(blank=True, help_text='Telefone para contato e envio de convites', max_length=20, verbose_name='Telefone/WhatsApp'),
        ),
    ]
