# Generated by Django 5.2.8 on 2025-12-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0033_despesa_comprovante_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True, verbose_name='Nome da Classe')),
                ('idade_min', models.PositiveIntegerField(verbose_name='Idade Mínima')),
                ('idade_max', models.PositiveIntegerField(verbose_name='Idade Máxima')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['idade_min'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['classe__idade_min', 'sexo', 'limite_min'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria_nome',
            field=models.CharField(max_length=50, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='label',
            field=models.CharField(max_length=80, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='limite_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Limite Máximo (kg)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='limite_min',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Limite Mínimo (kg)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='atletas.classe', verbose_name='Classe'),
        ),
    ]
