# Generated by Django 5.2.8 on 2025-12-01 14:28

from django.db import migrations


def seed_classes(apps, schema_editor):
    """Seed inicial das classes de idade"""
    Classe = apps.get_model("atletas", "Classe")

    classes = [
        ("FESTIVAL", 0, 6),
        ("SUB 9", 7, 8),
        ("SUB 11", 9, 10),
        ("SUB 13", 11, 12),
        ("SUB 15", 13, 14),
        ("SUB 18", 15, 17),
        ("SUB 21", 18, 20),
        ("SÊNIOR", 21, 29),
        ("VETERANOS", 30, 99),
    ]

    for nome, minimo, maximo in classes:
        Classe.objects.get_or_create(
            nome=nome,
            defaults={
                'idade_min': minimo,
                'idade_max': maximo
            }
        )


def reverse_seed_classes(apps, schema_editor):
    """Remove todas as classes criadas pelo seed"""
    Classe = apps.get_model("atletas", "Classe")
    Classe.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0034_create_classe_and_update_categoria'),
    ]

    operations = [
        migrations.RunPython(seed_classes, reverse_seed_classes),
    ]
