# Generated by Django 5.2.8 on 2025-12-01 14:28

from django.db import migrations
from decimal import Decimal


def seed_categorias(apps, schema_editor):
    """Seed inicial das categorias de peso para todas as classes e sexos"""
    # DESABILITADO: Categorias serão criadas manualmente via interface web (cadastrar_categoria)
    # Permite controle total sobre quais categorias são criadas
    pass


def reverse_seed_categorias(apps, schema_editor):
    """Remove todas as categorias criadas pelo seed"""
    Categoria = apps.get_model("atletas", "Categoria")
    Categoria.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0035_seed_classes'),
    ]

    operations = [
        # migrations.RunPython(seed_categorias, reverse_seed_categorias),  # DESABILITADO
    ]
