# Generated by Django 5.2.8 on 2025-12-01 14:28

from django.db import migrations
from decimal import Decimal


def seed_categorias(apps, schema_editor):
    """Seed inicial das categorias de peso para todas as classes e sexos"""
    Classe = apps.get_model("atletas", "Classe")
    Categoria = apps.get_model("atletas", "Categoria")

    # Verificar se existem classes
    classes = Classe.objects.all()
    if not classes.exists():
        print("⚠️  Aviso: Nenhuma classe encontrada. Execute a migration 0035_seed_classes primeiro.")
        return

    pesos = [
        ("Super Ligeiro", 0, 31),
        ("Ligeiro", 31, 34),
        ("Meio Leve", 34, 38),
        ("Leve", 38, 42),
        ("Meio Médio", 42, 47),
        ("Médio", 47, 52),
        ("Meio Pesado", 52, 57),
        ("Pesado", 57, 63),
        ("Super Pesado", 63, None),
    ]

    for classe in classes:
        classe_id = classe.id  # Usar ID diretamente para evitar problemas com ForeignKey em migrations
        for sexo in ["M", "F"]:
            for nome, minimo, maximo in pesos:
                if maximo is not None:
                    label = f"{classe.nome} - {sexo} - {nome} (-{maximo}kg)"
                else:
                    label = f"{classe.nome} - {sexo} - {nome} (+{minimo}kg)"

                # Verificar se já existe usando classe_id
                try:
                    categoria = Categoria.objects.get(
                        classe_id=classe_id,
                        sexo=sexo,
                        categoria_nome=nome
                    )
                    # Atualizar se já existe
                    categoria.limite_min = Decimal(str(minimo))
                    categoria.limite_max = Decimal(str(maximo)) if maximo is not None else None
                    categoria.label = label
                    categoria.save()
                except Categoria.DoesNotExist:
                    # Criar explicitamente usando classe_id ao invés do objeto classe
                    Categoria.objects.create(
                        classe_id=classe_id,
                        sexo=sexo,
                        categoria_nome=nome,
                        limite_min=Decimal(str(minimo)),
                        limite_max=Decimal(str(maximo)) if maximo is not None else None,
                        label=label
                    )


def reverse_seed_categorias(apps, schema_editor):
    """Remove todas as categorias criadas pelo seed"""
    Categoria = apps.get_model("atletas", "Categoria")
    Categoria.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0035_seed_classes'),
    ]

    operations = [
        migrations.RunPython(seed_categorias, reverse_seed_categorias),
    ]
