# Generated by Django 5.2.8 on 2025-12-01 14:28


from django.db import migrations
from decimal import Decimal


def ajustar_categorias_regulamento_5_nucleo(apps, schema_editor):
    """
    Ajusta as categorias conforme o Regulamento do 5º Núcleo Regional de Judô - 2025
    Baseado nas tabelas oficiais de classes e categorias masculinas e femininas
    """
    Classe = apps.get_model("atletas", "Classe")
    Categoria = apps.get_model("atletas", "Categoria")

    # Deletar todas as categorias existentes
    Categoria.objects.all().delete()

    # Definir categorias conforme o regulamento do 5º Núcleo
    # Formato: lista de tuplas (nome_classe, sexo, lista_de_categorias)
    # Cada categoria: (nome, limite_min, limite_max)
    
    categorias_regulamento = [
        # MASCULINO
        ("SUB 9", "M", [
            ("Super Ligeiro", 0, 23),
            ("Ligeiro", 23, 26),
            ("Meio Leve", 26, 29),
            ("Leve", 29, 32),
            ("Meio Médio", 32, 36),
            ("Médio", 36, 40),
            ("Meio Pesado", 40, 45),
            ("Pesado", 45, 50),
            ("Super Pesado", 50, None),
        ]),
        ("SUB 11", "M", [
            ("Super Ligeiro", 0, 26),
            ("Ligeiro", 26, 28),
            ("Meio Leve", 28, 30),
            ("Leve", 30, 33),
            ("Meio Médio", 33, 36),
            ("Médio", 36, 40),
            ("Meio Pesado", 40, 45),
            ("Pesado", 45, 50),
            ("Super Pesado", 50, None),
        ]),
        ("SUB 13", "M", [
            ("Super Ligeiro", 0, 28),
            ("Ligeiro", 28, 31),
            ("Meio Leve", 31, 34),
            ("Leve", 34, 38),
            ("Meio Médio", 38, 42),
            ("Médio", 42, 47),
            ("Meio Pesado", 47, 52),
            ("Pesado", 52, 60),
            ("Super Pesado", 60, None),
        ]),
        ("SUB 15", "M", [
            ("Super Ligeiro", 0, 40),
            ("Ligeiro", 40, 45),
            ("Meio Leve", 45, 50),
            ("Leve", 50, 55),
            ("Meio Médio", 55, 60),
            ("Médio", 60, 66),
            ("Meio Pesado", 66, 73),
            ("Pesado", 73, 81),
            ("Super Pesado", 81, None),
        ]),
        ("SUB 18", "M", [
            ("Super Ligeiro", 0, 50),
            ("Ligeiro", 50, 55),
            ("Meio Leve", 55, 60),
            ("Leve", 60, 66),
            ("Meio Médio", 66, 73),
            ("Médio", 73, 81),
            ("Meio Pesado", 81, 90),
            ("Pesado", 90, None),
        ]),
        ("SÊNIOR", "M", [
            ("Ligeiro", 0, 60),
            ("Meio Leve", 60, 66),
            ("Leve", 66, 73),
            ("Meio Médio", 73, 81),
            ("Médio", 81, 90),
            ("Meio Pesado", 90, 100),
            ("Pesado", 100, None),
        ]),
        ("VETERANOS", "M", [
            ("Ligeiro", 0, 60),
            ("Meio Leve", 60, 66),
            ("Leve", 66, 73),
            ("Meio Médio", 73, 81),
            ("Médio", 81, 90),
            ("Meio Pesado", 90, 100),
            ("Pesado", 100, None),
        ]),
        
        # FEMININO
        ("SUB 9", "F", [
            ("Super Ligeiro", 0, 23),
            ("Ligeiro", 23, 26),
            ("Meio Leve", 26, 29),
            ("Leve", 29, 32),
            ("Meio Médio", 32, 36),
            ("Médio", 36, 40),
            ("Meio Pesado", 40, 45),
            ("Pesado", 45, 50),
            ("Super Pesado", 50, None),
        ]),
        ("SUB 11", "F", [
            ("Super Ligeiro", 0, 26),
            ("Ligeiro", 26, 28),
            ("Meio Leve", 28, 30),
            ("Leve", 30, 33),
            ("Meio Médio", 33, 36),
            ("Médio", 36, 40),
            ("Meio Pesado", 40, 45),
            ("Pesado", 45, 50),
            ("Super Pesado", 50, None),
        ]),
        ("SUB 13", "F", [
            ("Super Ligeiro", 0, 28),
            ("Ligeiro", 28, 31),
            ("Meio Leve", 31, 34),
            ("Leve", 34, 38),
            ("Meio Médio", 38, 42),
            ("Médio", 42, 47),
            ("Meio Pesado", 47, 52),
            ("Pesado", 52, 60),
            ("Super Pesado", 60, None),
        ]),
        ("SUB 15", "F", [
            ("Super Ligeiro", 0, 36),
            ("Ligeiro", 36, 40),
            ("Meio Leve", 40, 44),
            ("Leve", 44, 48),
            ("Meio Médio", 48, 52),
            ("Médio", 52, 57),
            ("Meio Pesado", 57, 63),
            ("Pesado", 63, 70),
            ("Super Pesado", 70, None),
        ]),
        ("SUB 18", "F", [
            ("Super Ligeiro", 0, 40),
            ("Ligeiro", 40, 44),
            ("Meio Leve", 44, 48),
            ("Leve", 48, 52),
            ("Meio Médio", 52, 57),
            ("Médio", 57, 63),
            ("Meio Pesado", 63, 70),
            ("Pesado", 70, None),
        ]),
        ("SÊNIOR", "F", [
            ("Ligeiro", 0, 48),
            ("Meio Leve", 48, 52),
            ("Leve", 52, 57),
            ("Meio Médio", 57, 63),
            ("Médio", 63, 70),
            ("Meio Pesado", 70, 78),
            ("Pesado", 78, None),
        ]),
        ("VETERANOS", "F", [
            ("Ligeiro", 0, 48),
            ("Meio Leve", 48, 52),
            ("Leve", 52, 57),
            ("Meio Médio", 57, 63),
            ("Médio", 63, 70),
            ("Meio Pesado", 70, 78),
            ("Pesado", 78, None),
        ]),
        
        # FESTIVAL (mesmas categorias para M e F)
        ("FESTIVAL", "M", [
            ("Super Ligeiro", 0, 23),
            ("Ligeiro", 23, 26),
            ("Meio Leve", 26, 29),
            ("Leve", 29, 32),
            ("Meio Médio", 32, 36),
            ("Médio", 36, 40),
            ("Meio Pesado", 40, 45),
            ("Pesado", 45, 50),
            ("Super Pesado", 50, None),
        ]),
        ("FESTIVAL", "F", [
            ("Super Ligeiro", 0, 23),
            ("Ligeiro", 23, 26),
            ("Meio Leve", 26, 29),
            ("Leve", 29, 32),
            ("Meio Médio", 32, 36),
            ("Médio", 36, 40),
            ("Meio Pesado", 40, 45),
            ("Pesado", 45, 50),
            ("Super Pesado", 50, None),
        ]),
    ]

    # Criar categorias
    for nome_classe, sexo, lista_categorias in categorias_regulamento:
        try:
            classe = Classe.objects.get(nome=nome_classe)
            
            for nome_categoria, limite_min, limite_max in lista_categorias:
                # Formatar label
                if limite_max is not None:
                    if limite_min == 0:
                        label = f"{classe.nome} - {nome_categoria} (até {limite_max}kg)"
                    else:
                        label = f"{classe.nome} - {nome_categoria} (+{limite_min} a {limite_max}kg)"
                else:
                    label = f"{classe.nome} - {nome_categoria} (+{limite_min}kg)"
                
                Categoria.objects.create(
                    classe=classe,
                    sexo=sexo,
                    categoria_nome=nome_categoria,
                    limite_min=Decimal(str(limite_min)),
                    limite_max=Decimal(str(limite_max)) if limite_max is not None else None,
                    label=label
                )
        except Classe.DoesNotExist:
            print(f"⚠️ Classe '{nome_classe}' não encontrada. Pulando...")
            continue


def reverse_ajustar_categorias(apps, schema_editor):
    """Remove todas as categorias criadas"""
    Categoria = apps.get_model("atletas", "Categoria")
    Categoria.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0036_seed_categorias'),
    ]

    operations = [
        migrations.RunPython(ajustar_categorias_regulamento_5_nucleo, reverse_ajustar_categorias),
    ]
