# Generated by Django 5.2.8 on 2025-12-01 14:28


from django.db import migrations
from decimal import Decimal


def ajustar_categorias_regulamento_5_nucleo(apps, schema_editor):
    """
    Ajusta as categorias conforme o Regulamento do 5º Núcleo Regional de Judô - 2025
    Baseado nas tabelas oficiais de classes e categorias masculinas e femininas
    """
    # DESABILITADO: Categorias serão criadas manualmente via comando popular_categorias_regulamento
    # Evita erros durante o deploy
    pass


def reverse_ajustar_categorias(apps, schema_editor):
    """Remove todas as categorias criadas"""
    Categoria = apps.get_model("atletas", "Categoria")
    Categoria.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0036_seed_categorias'),
    ]

    operations = [
        # migrations.RunPython(ajustar_categorias_regulamento_5_nucleo, reverse_ajustar_categorias),  # DESABILITADO
    ]
