# Generated by Django 5.2.8 on 2025-12-03 17:14

import atletas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0037_ajustar_categorias_regulamento_5_nucleo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Organizador')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('logo', models.ImageField(blank=True, help_text='Logo do organizador (JPG, PNG)', null=True, upload_to=atletas.models.logo_organizador_upload_path, verbose_name='Logo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='academia',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academias', to='atletas.organizador', verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='cadastrooperacional',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastros_operacionais', to='atletas.organizador', verbose_name='Organizador'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='organizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos', to='atletas.organizador', verbose_name='Organizador'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizador', models.ForeignKey(blank=True, help_text='Organizador ao qual o usuário pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='atletas.organizador', verbose_name='Organizador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
    ]
