# Generated by Django 5.2.8 on 2025-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0039_add_senha_alterada_usuario_operacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariooperacional',
            name='senha_alterada',
            field=models.BooleanField(default=False, help_text='Indica se o usuário já alterou a senha no primeiro acesso', verbose_name='Senha Alterada'),
        ),
    ]
