# Generated by Codex to restore missing migration dependency chain.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("atletas", "0015_inscricao_status_workflow"),
    ]

    operations = []
