# Generated by Django 5.2.8 on 2025-12-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0040_usuariooperacional_senha_alterada'),
    ]

    operations = [
        migrations.AddField(
            model_name='luta',
            name='lado_atleta_a',
            field=models.CharField(choices=[('BRANCO', 'Branco'), ('AZUL', 'Azul')], default='BRANCO', max_length=10, verbose_name='Lado Atleta A'),
        ),
        migrations.AddField(
            model_name='luta',
            name='lado_atleta_b',
            field=models.CharField(choices=[('BRANCO', 'Branco'), ('AZUL', 'Azul')], default='AZUL', max_length=10, verbose_name='Lado Atleta B'),
        ),
    ]
