# Generated by Django 5.2.8 on 2026-01-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0041_add_lado_kimono_luta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='grupo_faixas',
            field=models.CharField(blank=True, choices=[('BRANCA_A_LARANJA', 'Branca a Laranja'), ('VERDE_A_PRETA', 'Verde a Preta'), ('BRANCA_A_VERDE', 'Branca a Verde'), ('ROXA_A_PRETA', 'Roxa a Preta')], db_index=True, help_text='Grupo técnico da chave (obrigatório a partir de SUB-18)', max_length=32, null=True, verbose_name='Grupo de Faixas'),
        ),
    ]
