# Generated by Django 5.2.8 on 2025-12-14 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('organization_id', models.UUIDField()),
                ('points_total', models.PositiveIntegerField()),
            ],
        ),
    ]
