# Generated by Django 5.2.8 on 2025-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='belt',
            field=models.CharField(choices=[('BRANCA', 'Branca'), ('CINZA', 'Cinza'), ('P_CINZA', 'P. Cinza'), ('AZUL', 'Azul'), ('P_AZUL', 'P. Azul'), ('AMARELA', 'Amarela'), ('P_AMARELA', 'P. Amarela'), ('LARANJA', 'Laranja'), ('P_LARANJA', 'P. Laranja'), ('VERDE', 'Verde'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], max_length=20),
        ),
    ]
