"""
Django settings for judocomp project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis de ambiente
RESET_ADMIN_PASSWORD = os.environ.get('RESET_ADMIN_PASSWORD')

# Senha obrigatória para acesso ao módulo operacional
# Esta senha deve ser definida como variável de ambiente ou alterada aqui
SENHA_OPERACIONAL = os.environ.get('SENHA_OPERACIONAL', 'SHIAI2024')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9c^_^fx1t+d!&xz-tbnogy)$cu7%)nmx2$i&frejw)l@$=wtj8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Permite acesso de qualquer IP (ajuste em produção)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'atletas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'atletas.middleware.MobileRedirectMiddleware',  # Detecção automática mobile/desktop
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'judocomp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'atletas.context_processors.campeonato_ativo',
            ],
        },
    },
]

WSGI_APPLICATION = 'judocomp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'atletas' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de Sessão - Segurança
# Sessões expiram quando o navegador fecha (não persistem) - NUNCA salvar senha em cache
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Sessões expiram após 1 hora de inatividade - Se expirar, exigir login novamente
SESSION_COOKIE_AGE = 3600  # 1 hora em segundos
# Cookie de sessão só via HTTPS em produção (ajustar quando tiver SSL)
SESSION_COOKIE_SECURE = False  # Mudar para True em produção com HTTPS
# Cookie de sessão não acessível via JavaScript (proteção XSS)
SESSION_COOKIE_HTTPONLY = True
# Cookie de sessão só no mesmo site
SESSION_COOKIE_SAMESITE = 'Lax'
# Não salvar sessão em cada requisição (melhor performance e segurança)
SESSION_SAVE_EVERY_REQUEST = False
# NUNCA permitir login automático - sempre exigir usuário e senha
