"""
Django settings for judocomp project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import mimetypes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carregar variáveis de ambiente
RESET_ADMIN_PASSWORD = os.environ.get('RESET_ADMIN_PASSWORD')

# Senha obrigatória para acesso ao módulo operacional
# NUNCA deixar senha hardcoded - sempre ler da variável de ambiente
senha_render = os.getenv("SENHA_OPERACIONAL")
if not senha_render:
    # Em produção (Render), a variável DEVE estar configurada
    if os.environ.get("RENDER"):
        import logging
        logger = logging.getLogger('django')
        logger.error("SENHA_OPERACIONAL não configurada no Render. Configure a variável de ambiente SENHA_OPERACIONAL.")
        raise ValueError("SENHA_OPERACIONAL não configurada. Configure a variável de ambiente SENHA_OPERACIONAL no Render.")
    # Em desenvolvimento local, usar valor padrão apenas para não quebrar
    # ATENÇÃO: Em produção, SEMPRE configure a variável de ambiente
    senha_render = 'SHIAI2024'  # Apenas para desenvolvimento local
    import logging
    logger = logging.getLogger('django')
    logger.warning("SENHA_OPERACIONAL não configurada. Usando valor padrão apenas para desenvolvimento local.")
SENHA_OPERACIONAL = senha_render


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key')


# SECURITY WARNING: don't run with debug turned on in production!
# Em desenvolvimento local, usar DEBUG=True
# Em produção (Render), usar variável de ambiente DEBUG=False
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://shiai-sistem.onrender.com',
    'https://*.shiai-sistem.onrender.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'atletas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Servir arquivos estáticos em produção
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Middleware de localização (deve vir após SessionMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'atletas.middleware.MobileRedirectMiddleware',  # Detecção automática mobile/desktop
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'judocomp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'atletas.context_processors.campeonato_ativo',
            ],
        },
    },
]

WSGI_APPLICATION = 'judocomp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get("RENDER"):
    # Ambiente de PRODUÇÃO (Render) usa disco persistente
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': "/opt/render/project/src/media/db.sqlite3",
        }
    }
else:
    # Ambiente LOCAL (normal)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

# Idiomas disponíveis no sistema
LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
    ('en', 'English'),
]

# Caminho para arquivos de tradução (locale)
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Formato de data e hora para português do Brasil
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
TIME_FORMAT = 'H:i'
YEAR_MONTH_FORMAT = 'F Y'
MONTH_DAY_FORMAT = 'd F'
SHORT_DATE_FORMAT = 'd/m/Y'
SHORT_DATETIME_FORMAT = 'd/m/Y H:i'
FIRST_DAY_OF_WEEK = 0  # Domingo (0 = Domingo, 1 = Segunda)

# Separador decimal e milhar
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT: Onde os arquivos estáticos serão coletados
# No Render, o caminho padrão já é correto (BASE_DIR / 'staticfiles')
# O Render automaticamente mapeia para /opt/render/project/src/staticfiles
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_DIRS: Onde o Django procura arquivos estáticos antes de coletar
STATICFILES_DIRS = [
    BASE_DIR / 'atletas' / 'static',
]

# WhiteNoise para servir arquivos estáticos em produção
# Usar CompressedStaticFilesStorage (mais simples e robusto)
# CompressedManifestStaticFilesStorage pode causar problemas com manifest.json
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de Sessão - Segurança
# Sessões expiram quando o navegador fecha (não persistem) - NUNCA salvar senha em cache
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Sessões expiram após 1 hora de inatividade - Se expirar, exigir login novamente
SESSION_COOKIE_AGE = 3600  # 1 hora em segundos
# Cookie de sessão só via HTTPS em produção (ajustar quando tiver SSL)
SESSION_COOKIE_SECURE = False  # Mudar para True em produção com HTTPS
# Cookie de sessão não acessível via JavaScript (proteção XSS)
SESSION_COOKIE_HTTPONLY = True
# Cookie de sessão só no mesmo site
SESSION_COOKIE_SAMESITE = 'Lax'
# Não salvar sessão em cada requisição (melhor performance e segurança)
SESSION_SAVE_EVERY_REQUEST = False
# NUNCA permitir login automático - sempre exigir usuário e senha

# Logging para capturar erros
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'class': 'logging.FileHandler',
            'level': 'ERROR',
            'filename': os.path.join(BASE_DIR, 'error.log'),
        },
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'atletas': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Adicionar tipos MIME para garantir que arquivos estáticos sejam servidos corretamente
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)
mimetypes.add_type("image/png", ".png", True)
mimetypes.add_type("image/jpeg", ".jpg", True)
mimetypes.add_type("image/jpeg", ".jpeg", True)
mimetypes.add_type("image/svg+xml", ".svg", True)
mimetypes.add_type("image/x-icon", ".ico", True)
