# Generated by Django 5.2.8 on 2025-12-14 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('category_code', models.CharField(max_length=50)),
                ('round_no', models.PositiveSmallIntegerField()),
                ('match_no', models.PositiveSmallIntegerField()),
                ('blue_registration_id', models.UUIDField()),
                ('white_registration_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FINISHED', 'Finished'), ('VOID', 'Void')], default='PENDING', max_length=20)),
                ('winner_side', models.CharField(blank=True, choices=[('BLUE', 'Blue'), ('WHITE', 'White')], max_length=10, null=True)),
                ('win_method', models.CharField(blank=True, choices=[('IPPON', 'Ippon'), ('WAZA_ARI', 'Waza-ari'), ('YOKO', 'Yoko'), ('HANSOKUMAKE', 'Hansokumake'), ('WO', 'Walk Over')], max_length=20, null=True)),
                ('fight_points_winner', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('finished_by_user_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_id', 'category_code'], name='matches_mat_event_i_e2e3d5_idx'), models.Index(fields=['event_id', 'round_no', 'match_no'], name='matches_mat_event_i_b2d6b4_idx')],
            },
        ),
    ]
