# Generated by Django 5.2.8 on 2025-12-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='matches_mat_event_i_e2e3d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='matches_mat_event_i_b2d6b4_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='blue_registration_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='match',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_no',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_no',
        ),
        migrations.RemoveField(
            model_name='match',
            name='white_registration_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner_side',
        ),
        migrations.AddField(
            model_name='match',
            name='blue_athlete_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='bracket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='brackets.bracket'),
        ),
        migrations.AddField(
            model_name='match',
            name='fight_points_loser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='white_athlete_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_athlete_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('FINISHED', 'Finished'), ('WALKOVER', 'Walkover')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='win_method',
            field=models.CharField(blank=True, choices=[('IPPON', 'Ippon'), ('WAZA_ARI', 'Waza-ari'), ('YUKO', 'Yuko'), ('HANSOKUMAKE', 'Hansokumake'), ('WO', 'Walk Over')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['bracket'], name='matches_mat_bracket_ebe93a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['bracket', 'round_number', 'match_number'], name='matches_mat_bracket_98cb55_idx'),
        ),
    ]
