# Generated by Django 5.2.8 on 2025-12-14 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('athlete_id', models.UUIDField()),
                ('organization_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WEIGHED', 'Weighed'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
